name: Python Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # You can specify the Python version

      # Step 3: Install Rust using actions-rs
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Step 4: Install maturin (to build Python bindings)
      - name: Install maturin
        run: pip install maturin

      # Step 5: Build Python bindings using maturin
      - name: Build Python bindings
        run: maturin develop

      # Step 6: Run Python tests using pytest
      - name: Run Python tests
        run: pytest tests/python

      # Optional: Check test results and handle failures
      - name: Check test results
        if: failure()
        run: echo "Some Python tests failed"
